apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "users-app.ingressName" . | quote }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}/(.*)
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "users-app.serviceName" . | quote }}
                port:
                  number: {{ int .Values.service.port }}